// <auto-generated />
using System;
using BestBankApp.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BestBankApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211213213443_BestBankAppV1")]
    partial class BestBankAppV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BestBankApp.Models.Clients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2")
                        .HasColumnName("BIRTHDAY");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<float>("Salary")
                        .HasColumnType("real")
                        .HasColumnName("SALARY");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SURNAME");

                    b.HasKey("Id");

                    b.ToTable("CLIENTS");
                });

            modelBuilder.Entity("BestBankApp.Models.Credits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AmountOfCredit")
                        .HasColumnType("real")
                        .HasColumnName("AMOUNT_OF_CREDIT");

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("CLIENT_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("Result")
                        .HasColumnType("bit")
                        .HasColumnName("RESULT");

                    b.Property<int>("TermsInMonths")
                        .HasColumnType("int")
                        .HasColumnName("TERMS_IN_MONTHS");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("CREDIT_APPLY");
                });

            modelBuilder.Entity("BestBankApp.Models.Credits", b =>
                {
                    b.HasOne("BestBankApp.Models.Clients", "CLIENTS")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CLIENTS");
                });
#pragma warning restore 612, 618
        }
    }
}
